name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    test:
        name: "${{ matrix.operating-system }} / PHP ${{ matrix.php-version }}"
        runs-on: ${{ matrix.operating-system }}
        continue-on-error: false

        strategy:
            matrix:
                operating-system: ['ubuntu-latest']
                php-version: ['8.2', '8.3']
                include:
                - operating-system: 'macos-latest'
                  php-version: '8.2'
                - operating-system: 'windows-latest'
                  php-version: '8.2'

        steps:
        - name: "Checkout code"
          uses: actions/checkout@v3

        - name: "Install PHP with extensions"
          uses: shivammathur/setup-php@v2
          with:
              coverage: "xdebug"
              extensions: "intl, mbstring, pdo_sqlite, zip"
              php-version: ${{ matrix.php-version }}
              tools: composer:v2

        - name: "Print php version"
          run: "php --version"

        - name: "Lancement des tests"
          run: .\vendor\bin\phpunit --coverage-html coverage --coverage-clover coverage/clover.xml

